### ISSUE TITLE
[Errno 121] Remote I/O error

### ISSUE THREAD

**Issue by abe7412** [adafruit/Adafruit_CircuitPython_SGP40#22]
Hello, 
I have been trying to use this driver on the sgp40 but I/O error occurs. tested the example script with different sensors.  `sudo i2cdetect -y 1` only shows up the address after running the script(error still occurs) if I run it again the device is no longer detected.

Using STEMMAQT wires. The device is wired to 3.3V
 
Any help is apperciated as I have been struggling with this issue for the past three days
![2023-07-13-135004_1920x1080_scrot](https://github.com/adafruit/Adafruit_CircuitPython_SGP40/assets/82842755/2a4e5dc8-8c37-423a-8f83-3b2907e6cd55)

**Comment by ladyada** [comment]
ok looks like we fixed this bug but it did not get released
i just published a release, try updating the library in an hour to get 1.3.15!
https://github.com/adafruit/Adafruit_CircuitPython_SGP40/releases
